### PR TITLE
Flatten children passed through Breadcrumbs

### PR DESCRIPTION
**Pull request by benja**
Related to https://github.com/fabric-ds/issues/issues/20.

* Fix bug where you couldn't have single children of Breadcrumbs
* Support fragment-nesting of children

### CODE REVIEW

**Review by digitalsadhu — COMMENTED** [review]
Should we be supporting nested child structures? This seems out of scope for the component no?

**Comment by benja** [comment]
> Should we be supporting nested child structures? This seems out of scope for the component no?

I honestly don't think we should, which is why I haven't updated the documentation. I still recommend passing the anchor elements as a direct child of Breadcrumbs, however, this makes it easier if people don't want to traverse through their objects and create a flat array themselves. It doesn't change any behavior other than parsing the children a bit better.

**Comment by digitalsadhu** [comment]
It adds more code though which means:
1. our already too large bundle size gets larger (however minimally)
2. its code we need to maintain

This feels to me like an application concern. We could support any number of data structures as input but we don't and I don't think we should. We provide a straight forward interface and users should then need to massage anything non started as needed. 

My 2 cents anyway.

**Comment by vsandvold** [comment]
Thank you for looking into this! I agree that supporting nested child components is something of an edge case, but this issue came up when we tried to render a nested list of links enclosed in React fragments. The Breadcrumb component behaved a bit strangely, which led to some confusion.

Fragments in JSX are of course transpiled to `React.createElement` in JS, but are eventually removed when rendered to HTML by `react-dom`. So when rendering the Breadcrumbs component with fragments, we go all the links as expected, just without the separators ("/"). The output appeared broken, and it wasn't clear to us what we had done wrong, since we expected fragments to be treated as "invisible" elements.

I believe the component should somehow prevent or at least warn about incorrect usage. How you do that is up to you, and I understand if you don't want to support links nested in fragments as originally suggested. But I prefer to get clear feedback on things I do wrong when developing, rather than just unpredictable behavior.

You're doing a great job, so please let me know how you want to move forward with this.

**Comment by trygve-lie** [comment]
As I understand the code, if one pass in a nested element structure, this will flatten it. A couple of red flags in my book here (some already mentioned in the comments):

 * This adds code to the bundle size for super corner cases
 * Unexpected behavior. If I pass in a nested structure, I expect to get that nested structure rendered out, not a different one.

If the component is not supporting nested structures that is fine, then a flat structure must be passed in. This should btw be clearly documented in the component.

> I believe the component should somehow prevent or at least warn about incorrect usage.

I've never heard of such; but is there a built in thing in React which can handle this? My point here is that I am not super keen on adding code to whats served to end users to cater for developer errors / DX.

**Comment by vsandvold** [comment]
@trygve-lie You have a lot of good points, and I agree that flattening any nested structure inside the component may hide and obfuscate the output you would expect to see. React fragments are a bit unusual in this sense, because they are by design hidden in the eventual output, and in that way also hiding the reason why the component doesn't work as expected.

I just want to give a few examples to make my point clear. Then you can of course decide what is best for Fabric.

If I pass in some nested child components to `Breadcrumbs` like this:
```jsx
<Breadcrumbs>
  <ul>
    <li>
      <a href="#/url/1">Eiendom</a>
    </li>
    <li>
      <a href="#/url/2">Bolig til salgs</a>
    </li>
    <li>
      <a href="#/url/3" aria-current="page">
        Oslo
      </a>
    </li>
  </ul>
</Breadcrumbs>
```

I would expect to see the same structure rendered in HTML like this:
```html
<nav class="flex space-x-8 -ml-8" aria-label="Her er du">
  <h2 class="u-screen-reader-only">Her er du</h2>
  <ul>
    <li>
      <a href="#/url/1">Eiendom</a>
    <li>
    <li>
      <a href="#/url/2">Bolig til salgs</a>
    <li>
    <li>
      <a href="#/url/3" aria-current="page">
    <li>
  </ul>
</nav>
```

In this case it's clear that my usage of the component is different than the one documented, and the rendered output helps me discover the error.

However, If I pass in some links nested in fragments, like this:
```jsx
const links = (
  <>
    <a href="#/url/1">Eiendom</a>
    <a href="#/url/2">Bolig til salgs</a>
    <a href="#/url/3" aria-current="page">
      Oslo
    </a>
  </>
)

<Breadcrumbs>
  {links}
</Breadcrumbs>
```

When this is rendered to HTML, it looks like this:
```html
<nav class="flex space-x-8 -ml-8" aria-label="Her er du">
  <h2 class="u-screen-reader-only">Her er du</h2>
  <a href="#/url/1">Eiendom</a>
  <a href="#/url/2">Bolig til salgs</a>
  <a href="#/url/3" aria-current="page">
</nav>
```

In comparison, the correct output would look like this:
```html
<nav class="flex space-x-8 -ml-8" aria-label="Her er du">
  <h2 class="u-screen-reader-only">Her er du</h2>
  <a href="#/url/1">Eiendom</a>
  <span aria-hidden="true" class="select-none">/</span>
  <a href="#/url/2">Bolig til salgs</a>
  <span aria-hidden="true" class="select-none">/</span>
  <a href="#/url/3" aria-current="page">
</nav>
```

These outputs are so similar that it's difficult to see why one flat list of links should work, while another (seemingly) flat list of links does not. Depending on you level of experience with React, you may not understand that fragments are nested in JS, and only flattened later when rendered by `react-dom`.

I'm not asking you to fix React, but it would be useful to get some kind of warning about incorrect usage from the component. It is not uncommon for React frameworks (and the runtime itself) to write warning to the console in development mode, with code that is removed from the production bundle by dead code elimination.

One common way of doing this is wrapping the dev code in a block like:
```js
if (process.env.NODE_ENV !== "production") {
   console.warn('your are doing something stupid');
}
```

Hopefully you can find a way to either make the component more resilient agains incorrect usage, improve the dev experience by providing helpful feedback, or add some docs on these edge cases.

**Comment by benja** [comment]
We've concluded that we probably should not be supporting individual edge cases for components like these in Fabric. I did, however, provide a solution above that flattens the object you are working with to the expected input. My suggestion is that we document this better, making it clearer that you are supposed to pass the anchor elements as direct children of the Breadcrumb. We'll also look into how to improve the DevEx when working specifically with children instead of props with types.

**Pull request closed without merging**
